---@alias Platform "computer" | "pocket" | "turtle"
---
---@class ApplicationMetadata
---@field version string
---@field platform Platform
---
---@class Application
---@field name string
---@field version string
---@field path string
---@field content? string
---
---@class UsedCraftingRecipe : CraftingRecipe
---@field isRoot boolean
---@field timesUsed integer
---
---[todo] find a better name
---@class CraftingDetails
---@field available ItemStock
---@field unavailable ItemStock
---@field leftOver ItemStock
---@field usedRecipes UsedCraftingRecipe[]
---
---@class Block
---@field name string
---@field state table
---@field tags table
---
