---@alias TaskType "provide-items" | "craft-items" | "allocate-ingredients"  | "craft-from-ingredients" | "build-chunk-storage" | "dig-chunk" | "build-chunk-pylon" | "empty-chunk-storage"
---
---@class Task
---@field id integer
---@field issuedBy string
---@field acceptedBy string?
---@field partOfTaskId integer?
---@field label string?
---@field message string?
---@field status TaskStatus
---@field type TaskType
---@field autoDelete boolean
---
---@alias TaskStatus "issued" | "accepted" | "finished" | "failed"
---
---@class ProvideItemsTask : Task
---@field type "provide-items"
---@field bufferId integer?
---@field transferredInitial boolean
---@field craftMissing boolean
---@field items ItemStock
---@field transferred ItemStock
---@field missing ItemStock
---@field missingDetails ItemStock
---@field to InventoryHandle
---
---@class ProvideItemsTaskReport
---@field wanted ItemStock
---@field found ItemStock
---@field missing ItemStock
---@field missingDetails ItemStock
---
---@class CraftItemsTask : Task
---@field type "craft-items"
---@field items ItemStock
---@field quantity integer
---@field crafted ItemStock
---@field to InventoryHandle?
---
---@class AllocateIngredientsTask : Task
---@field type "allocate-ingredients"
---@field bufferId integer?
---@field items ItemStock
---@field missing ItemStock
---@field craftingDetails CraftingDetails?
---
---@class CraftFromIngredientsTask : Task
---@field type "craft-from-ingredients"
---@field bufferId integer
---@field craftingDetails CraftingDetails
---@field usedRecipes UsedCraftingRecipe[]?
---@field crafted ItemStock
---
---@class ChunkTaskBase : Task
---@field chunkX integer
---@field chunkZ integer
---
---@class BuildChunkStorageTask : ChunkTaskBase
---@field type "build-chunk-storage"
---@field storageY integer
---@field chestLayers integer?
---
---@class DigChunkTask : ChunkTaskBase
---@field type "dig-chunk"
---@field storageY integer
---@field progress integer?
---
---@class BuildChunkPylonTask : ChunkTaskBase
---@field type "build-chunk-pylon"
---@field storageY integer
---@field initialized boolean
---@field disengaged boolean
---@field navigated boolean
---@field iterations BuildChunkPylonIteration[]?
---@field hubHome Vector
---@field hubFacing integer
---
---@class BuildChunkPylonIteration
---@field layers integer
---@field stock ItemStock
---@field materials string[]
---
---@class EmptyChunkStorageTask : ChunkTaskBase
---@field type "empty-chunk-storage"
---@field storageY integer
---@field home Vector?
---@field homeFacing integer?
---@field loadUp boolean
---@field isEmpty boolean
---
