---@class ItemDetail
---@field name string
---@field maxCount integer
---@field displayName string
---
---@alias ItemDetails table<string, ItemDetail>
---
---@class ItemStack
---@field name string
---@field count integer
---@field nbt? string
---@field maxCount? integer
---@field displayName? string
---@field tags? table<string, boolean>
---@alias ItemStacks table<integer, ItemStack>
---
---@class Inventory
---@field name string
---@field stacks ItemStacks
---@field slots table<integer, InventorySlot>
---@field allowAllocate boolean
---@field type InventoryType
---@field label? string
---@field items ItemStock
---
---@alias FurnaceInventoryTypes "furnace" | "furnace-config" | "furnace-input" | "furnace-output"
---@alias ComposterInventoryTypes "composter-config" | "composter-input"
---[todo] use enum instead
---@alias InventoryType "storage" | "io" | "dump" | "silo" | "silo:input" | "silo:output" | "shulker"  | "buffer" | "turtle-buffer" |"stash" | "quick-access" | "trash" | "ignore" | FurnaceInventoryTypes | ComposterInventoryTypes
---@alias InventorySlotTag "input" | "output" | "fuel" | "nameTag" | "configuration" | "buffer" | "withdraw"
---
---@class InventorySlot
---@field index integer
---@field tags InventorySlotTags
---@field permanent? boolean
---
---@class InventorySlotTags
---@field input? true
---@field output? true
---@field nameTag? true
---@field fuel? true
---@field configuration? true
---@field withdraw? true
---@field buffer? true
---
---@alias InventoryHandle integer | string | string[]
---
---@class AllocatedBuffer
---@field id integer
---@field taskId integer
---@field inventories string[]
---
---@alias TransferItemsMode "sequential" | "distribute"
---
---@class TransferOptions
---@field fromSequential? boolean
---@field toSequential? boolean
---@field rate? integer
---@field lockId? integer
---
