---@alias TaskType "provide-items" | "craft-items" | "allocate-ingredients"  | "craft-from-ingredients"
---
---@class Task
---@field id integer
---@field issuedBy string
---@field acceptedBy? string
---@field partOfTaskId? integer
---@field label? string
---@field status TaskStatus
---@field type TaskType
---@field autoDelete boolean
---
---@alias TaskStatus "issued" | "accepted" | "finished" | "failed"
---
---[todo] not yet implemented. purpose: get items from storage and craft those that are missing.
---@class ProvideItemsTask : Task
---@field type "provide-items"
---@field bufferId? integer
---@field transferredInitial boolean
---@field craftMissing boolean
---@field items ItemStock
---@field transferred ItemStock
---@field crafted ItemStock
---@field to InventoryHandle
---
---@class ProvideItemsTaskReport
---@field wanted ItemStock
---@field found ItemStock
---@field missing ItemStock
---
---@class CraftItemsTask : Task
---@field type "craft-items"
---@field items ItemStock
---@field quantity integer
---@field crafted ItemStock
---@field to? InventoryHandle
---
---@class AllocateIngredientsTask : Task
---@field type "allocate-ingredients"
---@field bufferId? integer
---@field items ItemStock
---@field missing ItemStock
---@field craftingDetails? CraftingDetails
---
---@class CraftFromIngredientsTask : Task
---@field type "craft-from-ingredients"
---@field bufferId integer
---@field craftingDetails CraftingDetails
---@field usedRecipes? UsedCraftingRecipe[]
---@field crafted ItemStock
---
