---@class TurtleDiskState
---In which directions the turtle should check for placed shulkers & disk drives that are "left over"
---due to a reboot/unload during shulker item transfer or orientating via disk drives. Key is the side,
---and value the block to break if it matches the probed one.
---@field cleanupSides table<PlaceSide, string>
---In which directions the turtle is about to try to place a disk drive.
---@field diskDriveSides PlaceSide[]
---In which directions the turtle is about to try to place a shulker.
---@field shulkerSides PlaceSide[]
---
---@class TurtleResumable
---@field name string
---@field home Vector
---@field randomSeed integer
---@field initialState SimulationState
---@field args string[]
---@field state unknown
---@field options TurtleResumableOptions
---@field fnName string?
---
---@class TurtleResumableOptions
---@field requireItems boolean?
---@field requireFuel boolean?
---@field requireShulkers boolean?
---@field additionalRequiredItems ItemStock?
---
---@alias DigSide "top" | "front" | "bottom"
---@alias PlaceSide "top" | "front" | "bottom"
---@alias MoveDirection "forward" | "back" | "up" | "down"
