---@class TurtleDiskState
---In which directions the turtle should check for placed shulkers & disk drives that are "left over"
---due to a reboot/unload during shulker item transfer or orientating via disk drives. Key is the side,
---and value the block to break if it matches the probed one.
---@field cleanupSides table<PlaceSide, string>
---In which directions the turtle is about to try to place a disk drive.
---@field diskDriveSides PlaceSide[]
---In which directions the turtle is about to try to place a shulker.
---@field shulkerSides PlaceSide[]
---
---@class TurtleResumable
---@field name string
---@field home Vector
---@field randomSeed integer
---@field initialState SimulationState
---@field args string[]
---@field state unknown
---
---@class SimulationState
---@field fuel integer
---@field facing integer
---@field position Vector
