---@alias QuestType "provide-items" | "craft-item" | "transfer-items" | "dance"
---
---@class Quest
---@field id integer
---@field issuedBy string
---@field acceptedBy? string
---@field partOfQuestId? integer
---@field label? string
---@field status QuestStatus
---@field type QuestType
---
---@alias QuestStatus "issued" | "accepted" | "finished" | "failed"
---
---@class ProvideItemsQuest : Quest
---@field type "provide-items"
---@field craftMode "missing" | "all" | "none"
---@field transferredInitial boolean
---@field craftMissingQuestId? integer
---@field items ItemStock
---@field to string[]
---@field toTag InventorySlotTag
---
---@class CraftItemQuest : Quest
---@field type "craft-item"
---@field item string
---@field quantity integer
---@field bufferId? integer
---@field craftingDetails? CraftingDetails
---@field usedRecipes? UsedCraftingRecipe[]
---
---@class TransferItemsQuest : Quest
---@field type "transfer-items"
---@field to string[]
---@field toTag InventorySlotTag
---@field items ItemStock
---@field bufferId? integer
---@field found? ItemStock 
---@field transferred ItemStock
---@field transferredAll boolean
---
---@class DanceQuest : Quest
---@field type "dance"
---@field duration integer
