---@alias TaskType "provide-items" | "allocate-ingredients" | "craft-item" | "transfer-items" | "dance"
---
---@class Task
---@field id integer
---@field issuedBy string
---@field acceptedBy? string
---@field partOfTaskId? integer
---@field label? string
---@field status TaskStatus
---@field type TaskType
---
---@alias TaskStatus "issued" | "accepted" | "finished" | "failed"
---
---@class ProvideItemsTask : Task
---@field type "provide-items"
---@field craftMode "missing" | "all" | "none"
---@field transferredInitial boolean
---@field craftMissingTaskId? integer
---@field items ItemStock
---@field to string[]
---@field toTag InventorySlotTag
---
---@class CraftItemTask : Task
---@field type "craft-item"
---@field item string
---@field quantity integer
---@field bufferId? integer
---@field craftingDetails? CraftingDetails
---@field usedRecipes? UsedCraftingRecipe[]
---
---@class TransferItemsTask : Task
---@field type "transfer-items"
---@field to string[]
---@field toTag InventorySlotTag
---@field items ItemStock
---@field bufferId? integer
---@field found? ItemStock 
---@field transferred ItemStock
---@field transferredAll boolean
---
---@class DanceTask : Task
---@field type "dance"
---@field duration integer
