---@alias TaskType "provide-items" | "allocate-ingredients" | "gather-items" | "gather-items-via-player" | "craft-items" | "craft-from-ingredients" | "transfer-items" | "dance"
---
---@class Task
---@field id integer
---@field issuedBy string
---@field acceptedBy? string
---@field partOfTaskId? integer
---@field label? string
---@field status TaskStatus
---@field type TaskType
---
---@alias TaskStatus "issued" | "accepted" | "finished" | "failed"
---
---[todo] not yet implemented. purpose: get items from storage and craft those that are missing.
---@class ProvideItemsTask : Task
---@field type "provide-items"
---@field craftMode "missing" | "all" | "none"
---@field transferredInitial boolean
---@field craftMissingTaskId? integer
---@field items ItemStock
---@field to string[]
---@field toTag InventorySlotTag
---
---@class AllocateIngredientsTask : Task
---@field type "allocate-ingredients"
---@field bufferId? integer
---@field items ItemStock
---@field craftingDetails? CraftingDetails
---
---@class GatherItemsTask : Task
---@field type "gather-items"
---@field items ItemStock
---@field to string[]
---@field toTag InventorySlotTag
---@field bufferId? integer
---
---@class GatherItemsViaPlayerTask : Task
---@field type "gather-items-via-player"
---@field items ItemStock
---@field open ItemStock
---@field to string[]
---@field toTag InventorySlotTag
---@field bufferId? integer
---
----[todo] allow multiple items
---@class CraftItemsTask : Task
---@field type "craft-items"
---@field item string
---@field quantity integer
---
---[todo] allow multiple items
---@class CraftFromIngredientsTask : Task
---@field type "craft-from-ingredients"
---@field bufferId integer
---@field craftingDetails CraftingDetails
---@field usedRecipes? UsedCraftingRecipe[]
---
---@class TransferItemsTask : Task
---@field type "transfer-items"
---@field toBufferId? integer
---@field to? string[]
---@field toTag? InventorySlotTag
---@field items ItemStock
---@field bufferId? integer
---@field found? ItemStock 
---@field transferred ItemStock
---@field transferredAll boolean
---
---@class DanceTask : Task
---@field type "dance"
---@field duration integer
