---@alias SubwayStationType "hub"|"endpoint"|"platform"|"switch"
---
---@class SubwayStation
---@field id string
---@field name string
---@field label? string
---@field type SubwayStationType
---@field tracks SubwayTrack[]
---
---@class SubwayTrack
---@field to string
---@field signal number
---@field duration? number
---
